export const products = [
    { id: 1,
      title: 'Tarta Bombon',
      description: 'Masa quebrada de chocolate. Rellena con dulce de Leche con licor. Cubierta con ganache de chocolate. Deliciosa!!!',
      image: '/images/Bombon.jpg',
      precio: "$12500",
      categoria: "tartas"
    },
    { id: 2,
      title: 'Tarta Lemon Pie',
      description: 'Masa sable de vainilla super sabrosa. Con un relleno de crema de limón único y cuabierta con el mejor merengue italiano. Impresionante',
      image: '/images/LemonPie.jpg',
      precio: "$13500",
      categoria: "tartas"
    },
    { id: 3,
      title: 'Tarta de Duraznos',
      description: 'Base de masa de vainilla súper sabrosa. Relleno de crema chantilly y cubierta con duraznos. Fresca y exquisita.',
      image: '/images/Durazno.jpg',
      precio: "$13000",
      categoria: "tartas"
    },
    { id: 4,
      title: 'Tarta de Durazno y pastelera',
      description: 'Base de masa de vainilla súper sabrosa. Relleno de crema pastelera y cubierta con duraznos. Fresca y exquisita.',
      image: '/images/Durazno.jpg',
      precio:"$12500",
      categoria: "tartas"
    },
    { id: 5,
      title: 'Tarta de Frutillas',
      description: 'Base de masa de vainilla súper sabrosa. Relleno de crema chantilly y cubierta con frutillas. Muy rica.',
      image: '/images/Frutilla.jpg',
      precio:"$13500",
      categoria: "tartas"
    },
    { id:6,
      title: 'Tarta de Dulce de Leche y Coco',
      description: 'Base de masa de vainilla. Relleno de crumble de coco y Dulce de Leche delicioso. Impreionante!.',
      image: '/images/Coco.jpg',
      precio:"$13000",
      categoria: "tartas"
    },
    { id:7,
      title: 'Postre tipo Balcarce',
      description: 'Base de masa de pionono. Relleno con merenguitos, salsa de chocolate, crema chamtully y nueces. Increíble!.',
      image: '/images/BalcarPostre.jpg',
      precio:"$19000",
      categoria: "postres"
    },
    { id:8,
      title: 'Torta de ricotta',
      description: 'Base y tapa de masa de vainilla. Relleno de ricotta y crema pastelera con un toque de Dulce de Leche. Impreionante!.',
      image: '/images/Ricotta.jpg',
      precio:"$18000",
      categoria: "postres"
    },
    { id:9,
      title: 'Cheesecake ',
      description: 'Base de galleta molida. Cake de queso con culis de frutos rojos o frutilla. Incomparable!.',
      image: '/images/Cheesecake.jpg',
      precio:"$18500",
      categoria: "postres"
    },
  ];